In [4]:
import numpy as np

Create an array A with shape (3,3,3) and array B with shape (1,3,3) and perform the 
following:
1. Check the attributes of the array A.
2. Create a subarray by accessing sheet 0 (zero), all rows, flip order of all columns.
3. Reshape the array A into 2-Dimension array.
4. Addition and Multiplication with broadcasting.
5. Sum of all the elements, sum of each row and column of array A.

In [47]:
a=np.random.randint(2,20 ,size=(3,3,3))
b=np.random.randint(20,40,size=(1,3,3))
print(a)
print("\n")
print(b)

[[[ 6  6 16]
  [16  9  2]
  [17 15 16]]

 [[ 7 16  5]
  [17 15  6]
  [ 5 16 13]]

 [[ 3 11  5]
  [ 9 10  8]
  [18  6 14]]]


[[[20 35 21]
  [24 28 37]
  [34 31 24]]]


In [48]:
#attribute a
print("shape:",a.shape)
print("dimesion",a.ndim)
print("size",a.size)
print("types",a.dtype)

shape: (3, 3, 3)
dimesion 3
size 27
types int32


In [49]:
sub_a=a[0,:,::-1]
print(sub_a)

[[16  6  6]
 [ 2  9 16]
 [16 15 17]]


In [51]:
two_dim=a.reshape((9,3))
two_dim

array([[ 6,  6, 16],
       [16,  9,  2],
       [17, 15, 16],
       [ 7, 16,  5],
       [17, 15,  6],
       [ 5, 16, 13],
       [ 3, 11,  5],
       [ 9, 10,  8],
       [18,  6, 14]])

In [57]:
addition=a+b
print(addition)
print(addition.shape)

[[[26 41 37]
  [40 37 39]
  [51 46 40]]

 [[27 51 26]
  [41 43 43]
  [39 47 37]]

 [[23 46 26]
  [33 38 45]
  [52 37 38]]]
(3, 3, 3)


In [58]:
mul=a*b
print(mul)
print(mul.shape)

[[[120 210 336]
  [384 252  74]
  [578 465 384]]

 [[140 560 105]
  [408 420 222]
  [170 496 312]]

 [[ 60 385 105]
  [216 280 296]
  [612 186 336]]]
(3, 3, 3)


In [66]:
print("sum of all value in array a:\n",np.sum(a))
print("sum of the each row of array a:\n",np.sum(a,axis=1))
print("sum of the each column of array a:\n",np.sum(a,axis=2))

sum of all value in array a:
 287
sum of the each row of array a:
 [[39 30 34]
 [29 47 24]
 [30 27 27]]
sum of the each column of array a:
 [[28 27 48]
 [28 38 34]
 [19 27 38]]


In [71]:
#practice

In [77]:
a1=np.arange(2,42,2)
a2=a1.reshape(4,5)
a2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

In [79]:
np.random.rand(3,3)

array([[0.15355585, 0.16270479, 0.91028939],
       [0.34308936, 0.156922  , 0.2809797 ],
       [0.31499937, 0.85561794, 0.48076717]])

Create an array X using a routine of shape (4, 4) with values ranging from -10 to 10 and
compute the following:
1. Matrix rank of array
2. Determinant of an array and round the result for decimal place 1
3. Inverse of a matrix
4. Eigenvalues and right eigenvectors of a square array
5. Create subarrays of x into x1 (first 3 rows & 3 columns) and x2 (last 3 rows & last 3columns) and compute matrix product of two arrays (x1, x2)
6. Create subarrays of x into y1 (every other element of row & column) and y2 (everyother element from last row and last column) and compute dot and inner product of (y1, y2)
7. Raise a square matrix x1 to the power 3

In [82]:
x=np.random.randint(-10,10,(4,4))
print(x)

[[  2   7   8  -7]
 [ -1  -3   9  -2]
 [ -4  -8   6 -10]
 [ -4  -5  -7   5]]


In [87]:
print("rank of the matrix", np.linalg.matrix_rank(x))

rank of the matrix 4


In [91]:
print("determinent:",round(np.linalg.det(x),1))

determinent: -2610.0


In [92]:
print("diagonal:",np.diagonal(x))

diagonal: [ 2 -3  6  5]


In [94]:
#sum of the diagonal
print(sum(np.diagonal(x)))

10


In [103]:
eig_value,eig_vector=np.linalg.eig(x)
print("eigen value \n",eig_value)
print("eigen vector \n",eig_vector)

eigen value 
 [-2.88809395+0.j         -0.4477232 +8.08480004j -0.4477232 -8.08480004j
 13.78354035+0.j        ]
eigen vector 
 [[-0.82041743+0.j          0.53095025+0.j          0.53095025-0.j
  -0.68573176+0.j        ]
 [ 0.51888661+0.j         -0.01107036+0.52248881j -0.01107036-0.52248881j
  -0.1873849 +0.j        ]
 [-0.12962976+0.j         -0.50226383+0.15825172j -0.50226383-0.15825172j
  -0.28250402+0.j        ]
 [-0.20215846+0.j         -0.39942627+0.09011555j -0.39942627-0.09011555j
   0.64408877+0.j        ]]


In [120]:
x1=x[:3,:3]
x2=x[1:,1:]
print("matrix multiplication:\n",np.dot(x1,x2))

matrix multiplication:
 [[-102    4  -34]
 [ -18  -90   77]
 [  46 -126  118]]


In [125]:
y1=x[::2,::2]
print(y1,"\n")
y2=x[::-2,::-2]
print(y2)
print("inner matrix:\n",np.inner(y1,y2))

[[ 2  8]
 [-4  6]] 

[[ 5 -5]
 [-2 -3]]
inner matrix:
 [[-30 -28]
 [-50 -10]]


In [126]:
print(np.power(x1,3))

[[   8  343  512]
 [  -1  -27  729]
 [ -64 -512  216]]


Create a structured array with the columns specified in the table below and perform the 
following:
1. Create a copy of the original array and perform the operations on it.
2. Sort the array by ‘Salary’ column in descending order.
3. Create an array by accessing ‘Age’ column and perform an indirect sort on it to return array of indices, using these indices construct a sorted array via fancy indexing.
4. Create a subset of array where ‘Experience’ is greater than 20 (use where() function).
5. Create an array ‘Incentive’ by adding 200 to the salary for those who are having work experience more than 20 years.
6. Access ‘Name’, ‘Gender’ and ‘Age’ columns at once using a list of field names.
7. Access last two names of the array ‘Name’.
8. Use shorter syntax method to display the minimum, average, maximum and standard deviation of the salary.
9. Are all of the employees male?
10. How many employees are there with working experience between 15.2 and 24.5?


In [46]:
dt=np.dtype([('Name','S20'),('Gender','S20'),('Age','i4'),('Experience','float64'),('Salary','i')])
p_table= np.array([('cathy','F',45,15.5,2711), 
 ('Xavier','M',78,9.2,3420), 
 ('Alexander','M',61,24.1,3275), 
 ('Andrew','M',44,15.6,5988), 
 ('isabelle','F',45,15.9,7444),
 ('Natasha','F',61,24.5,1646), 
 ('Henry','M',60,24.5,1646), 
 ('David','M',47,15.3,9120)], dtype=dt) 
print(p_table)

[(b'cathy', b'F', 45, 15.5, 2711) (b'Xavier', b'M', 78,  9.2, 3420)
 (b'Alexander', b'M', 61, 24.1, 3275) (b'Andrew', b'M', 44, 15.6, 5988)
 (b'isabelle', b'F', 45, 15.9, 7444) (b'Natasha', b'F', 61, 24.5, 1646)
 (b'Henry', b'M', 60, 24.5, 1646) (b'David', b'M', 47, 15.3, 9120)]


In [47]:
b=p_table.copy()

In [48]:
(b[np.argsort(b["Salary"])])[::-1]

array([(b'David', b'M', 47, 15.3, 9120),
       (b'isabelle', b'F', 45, 15.9, 7444),
       (b'Andrew', b'M', 44, 15.6, 5988),
       (b'Xavier', b'M', 78,  9.2, 3420),
       (b'Alexander', b'M', 61, 24.1, 3275),
       (b'cathy', b'F', 45, 15.5, 2711), (b'Henry', b'M', 60, 24.5, 1646),
       (b'Natasha', b'F', 61, 24.5, 1646)],
      dtype=[('Name', 'S20'), ('Gender', 'S20'), ('Age', '<i4'), ('Experience', '<f8'), ('Salary', '<i4')])

In [49]:
#fancy indexing
age_1=b["Age"]
ind=np.argsort(age_1)
b[ind]

array([(b'Andrew', b'M', 44, 15.6, 5988),
       (b'cathy', b'F', 45, 15.5, 2711),
       (b'isabelle', b'F', 45, 15.9, 7444),
       (b'David', b'M', 47, 15.3, 9120), (b'Henry', b'M', 60, 24.5, 1646),
       (b'Alexander', b'M', 61, 24.1, 3275),
       (b'Natasha', b'F', 61, 24.5, 1646),
       (b'Xavier', b'M', 78,  9.2, 3420)],
      dtype=[('Name', 'S20'), ('Gender', 'S20'), ('Age', '<i4'), ('Experience', '<f8'), ('Salary', '<i4')])

In [50]:
b[np.where(b["Experience"]>20)]

array([(b'Alexander', b'M', 61, 24.1, 3275),
       (b'Natasha', b'F', 61, 24.5, 1646),
       (b'Henry', b'M', 60, 24.5, 1646)],
      dtype=[('Name', 'S20'), ('Gender', 'S20'), ('Age', '<i4'), ('Experience', '<f8'), ('Salary', '<i4')])

In [55]:
b[np.where(b["Experience"]>20),]["Salary"]+200

array([[3475, 1846, 1846]], dtype=int32)

In [194]:
b[["Name","Gender","Age"]]

array([(b'cathy', b'F', 45), (b'Xavier', b'M', 78),
       (b'Alexander', b'M', 61), (b'Andrew', b'M', 44),
       (b'isabelle', b'F', 45), (b'Natasha', b'F', 61),
       (b'Henry', b'M', 60), (b'David', b'M', 47)],
      dtype={'names':['Name','Gender','Age'], 'formats':['S20','S20','<i4'], 'offsets':[0,20,40], 'itemsize':56})

In [195]:
b["Name"][-2:]

array([b'Henry', b'David'], dtype='|S20')

In [196]:
b[["Name","Gender","Age"]][:2]

array([(b'cathy', b'F', 45), (b'Xavier', b'M', 78)],
      dtype={'names':['Name','Gender','Age'], 'formats':['S20','S20','<i4'], 'offsets':[0,20,40], 'itemsize':56})

In [197]:
print("minimum of salary",np.min(b["Salary"]))
print("maximum of salary",np.max(b["Salary"]))
print("average of salary",np.average(b["Salary"]))
print("standard deviation of salary",round(np.std(b["Salary"]),4))

minimum of salary 1646
maximum of salary 9120
average of salary 4406.25
standard deviation of salary 2605.608


In [198]:
b[b["Gender"]=="M"]

array([], shape=(0, 8),
      dtype=[('Name', 'S20'), ('Gender', 'S20'), ('Age', '<i4'), ('Experience', '<f8'), ('Salary', '<i4')])

In [204]:
print("number of persons experience between 15.2 and 24.5 is :",np.count_nonzero(b[(b["Experience"]>15.2)&(b["Experience"]<24.5)]))

number of persons experience between 15.2 and 24.5 is : 5


In [206]:
b

array([(b'cathy', b'F', 45, 15.5, 2711),
       (b'Xavier', b'M', 78,  9.2, 3420),
       (b'Alexander', b'M', 61, 24.1, 3275),
       (b'Andrew', b'M', 44, 15.6, 5988),
       (b'isabelle', b'F', 45, 15.9, 7444),
       (b'Natasha', b'F', 61, 24.5, 1646),
       (b'Henry', b'M', 60, 24.5, 1646), (b'David', b'M', 47, 15.3, 9120)],
      dtype=[('Name', 'S20'), ('Gender', 'S20'), ('Age', '<i4'), ('Experience', '<f8'), ('Salary', '<i4')])

In [210]:
# name of peoples who age is greater than 50
b[b["Age"]>50]["Name"]

array([b'Xavier', b'Alexander', b'Natasha', b'Henry'], dtype='|S20')

In [1]:
#practice

In [8]:
print(np.__version__)

1.21.5


In [11]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [19]:
#Write a NumPy program to test whether none of the elements of a given array are zero. 
a1=np.arange(1,6)
print("whether none of the elements of a given array are zero:",np.all(a1))
a2=np.array([1,0,6,7,2,3])
print("whether none of the elements of a given array are zero:",np.all(a2))

whether none of the elements of a given array are zero: True
whether none of the elements of a given array are zero: False


In [21]:
#Write a NumPy program to test if any of the elements of a given array are non-zero. 
a1=np.array([0,0,0,0])
print("any of the elements of a given array are zero:",np.any(a1))
a2=np.array([1,0,6,7,2,3])
print("any of the elements of a given array are zero:",np.any(a2))

any of the elements of a given array are zero: False
any of the elements of a given array are zero: True


In [40]:
#flatten the given list
m1=[[1,2,3,4],[3,4,5,6],[4,5,6,7],[2,3,4,1]]
print(m1)
#flatten the list
m2=np.array(m1)
print("flatten the array \n",m2.reshape((m2.size)))

[[1, 2, 3, 4], [3, 4, 5, 6], [4, 5, 6, 7], [2, 3, 4, 1]]
flatten the array 
 [1 2 3 4 3 4 5 6 4 5 6 7 2 3 4 1]


In [42]:
#Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array.
l1=[12,34.5,4,53,12]
arr1=np.array(l1)
print(arr1)

[12.  34.5  4.  53.  12. ]


In [52]:
#Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.
arr1=np.arange(2,11)
print(arr1)
arr2=arr1.reshape(3,3)
print("3X3 matrix is:\n",arr2)

[ 2  3  4  5  6  7  8  9 10]
3X3 matrix is:
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [54]:
arr1=np.arange(2,11).reshape(3,3)
print(arr1)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [58]:
#Write a NumPy program to create a null vector of size 10 and update the sixth value to 11
all_zero=np.zeros(10)
print("null vector of size 10",all_zero)
all_zero[5]=11
print("updated array",all_zero)

null vector of size 10 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
updated array [ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


In [60]:
#Write a NumPy program to create an array with values ranging from 12 to 38 and reverse an array
arr1=np.arange(12,38)
rev_arr1=arr1[::-1]
print(arr1)
print("reversed array",rev_arr1)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
reversed array [37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [63]:
#Write a NumPy program to convert an array to a floating type
arr1=np.arange(1,5)
print(arr1)
arr2=np.asfarray(arr1)
print("floated value:",arr2)

[1 2 3 4]
floated value: [1. 2. 3. 4.]


In [70]:
#Write a NumPy program to create a 2D array with 1 on the border and 0 inside.
arr1=np.ones((6,6))
arr1[1:len(arr1)-1,1:len(arr1)-1]=0
arr1

array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [75]:
#other method
arr1=np.ones((6,6))
print("oroginal array: \n",arr1)
arr1[1:-1,1:-1]=0
print("updated array:\n",arr1)

oroginal array: 
 [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
updated array:
 [[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [86]:
# Write a NumPy program to create an 8x8 matrix and fill it with a checkerboard pattern.
arr1=np.ones((8,8))
print(arr1)
arr1[1::2,::2]=0
arr1[::2,1::2]=0
print("checkerboard pattern: \n",arr1)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
checkerboard pattern: 
 [[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [62]:
#Write a NumPy program to create an empty and full array.

empty_array=np.empty((3,3))
print(empty_array)

full_array=np.full((3,3),4)
print("full array: \n",full_array)

[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 8.22125235e-321]
 [1.78019082e-306 1.37959740e-306 2.29178686e-312]]
full array: 
 [[4 4 4]
 [4 4 4]
 [4 4 4]]


In [88]:
#NumPy program to convert a list and tuple into arrays
l1=[1,2,3,4,5]
arr1=np.array(l1)
print(arr1)
t1=(1,2,3)
arr2=np.array(t1)
print(arr2)

[1 2 3 4 5]
[1 2 3]


In [90]:
#slicing
ar1=np.arange(10)
ar1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
ar1_slice=ar1[3:8]
print(ar1_slice)

[3 4 5 6 7]


In [92]:
ar1_slice[3]=24

In [93]:
print(ar1)

[ 0  1  2  3  4  5 24  7  8  9]


In [5]:
#boolean slicing
name=np.array(["nidhi","niks","pokemon","nidhi"])
print(name)
arr1=np.random.rand(4,6)
print(arr1)

['nidhi' 'niks' 'pokemon' 'nidhi']
[[0.46076655 0.0970108  0.710432   0.18559023 0.93440634 0.32114264]
 [0.57471865 0.15055508 0.65157554 0.61518664 0.03095582 0.11423976]
 [0.72317268 0.23421574 0.35387872 0.1982846  0.92523841 0.82493669]
 [0.19150081 0.83654268 0.2945381  0.17943759 0.03819598 0.73224671]]


In [6]:
name=="nidhi"

array([ True, False, False,  True])

In [7]:
arr1[name=="nidhi"]

array([[0.46076655, 0.0970108 , 0.710432  , 0.18559023, 0.93440634,
        0.32114264],
       [0.19150081, 0.83654268, 0.2945381 , 0.17943759, 0.03819598,
        0.73224671]])

In [10]:
# want to access the last 3 columnn
arr1[name=="nidhi",-3:]

array([[0.18559023, 0.93440634, 0.32114264],
       [0.17943759, 0.03819598, 0.73224671]])

In [12]:
#except nidhi details of others 
arr1[~(name=="nidhi")]

array([[0.57471865, 0.15055508, 0.65157554, 0.61518664, 0.03095582,
        0.11423976],
       [0.72317268, 0.23421574, 0.35387872, 0.1982846 , 0.92523841,
        0.82493669]])

In [13]:
s1=arr1[(name=="nidhi")|(name=="niks")]
print(s1)

[[0.46076655 0.0970108  0.710432   0.18559023 0.93440634 0.32114264]
 [0.57471865 0.15055508 0.65157554 0.61518664 0.03095582 0.11423976]
 [0.19150081 0.83654268 0.2945381  0.17943759 0.03819598 0.73224671]]


In [14]:
s1[0,0]=1
print(s1)

[[1.         0.0970108  0.710432   0.18559023 0.93440634 0.32114264]
 [0.57471865 0.15055508 0.65157554 0.61518664 0.03095582 0.11423976]
 [0.19150081 0.83654268 0.2945381  0.17943759 0.03819598 0.73224671]]


here it create the copy of the main array(arr1). if we update it does not effect to the main array

In [15]:
arr1

array([[0.46076655, 0.0970108 , 0.710432  , 0.18559023, 0.93440634,
        0.32114264],
       [0.57471865, 0.15055508, 0.65157554, 0.61518664, 0.03095582,
        0.11423976],
       [0.72317268, 0.23421574, 0.35387872, 0.1982846 , 0.92523841,
        0.82493669],
       [0.19150081, 0.83654268, 0.2945381 , 0.17943759, 0.03819598,
        0.73224671]])

In [17]:
#fancy indexing
arr2=np.arange(32).reshape(8,4)
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [23]:
#select 2,4,6,8 rows
arr3=arr2[[1,3,5,7]]
arr3[1,0]=100
print(arr3)

[[  4   5   6   7]
 [100  13  14  15]
 [ 20  21  22  23]
 [ 28  29  30  31]]


In [24]:
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [33]:
arr2[[0,2,4,6],[3,0,1,0]]       #(0,3) (2,0) (4,1) (6,0)

array([ 3,  8, 17, 24])

In [29]:
arr4=arr2[:,3:]
arr4
arr4[2]=200
arr4

array([[  3],
       [  7],
       [200],
       [ 15],
       [ 19],
       [ 23],
       [ 27],
       [ 31]])

In [31]:
arr2

array([[  0,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10, 200],
       [ 12,  13,  14,  15],
       [ 16,  17,  18,  19],
       [ 20,  21,  22,  23],
       [ 24,  25,  26,  27],
       [ 28,  29,  30,  31]])

In [39]:
#unary function
arr1=np.array([[4,16],[36,81]])
print(arr1)
print("square root of the each element \n",np.sqrt(arr1))

[[ 4 16]
 [36 81]]
square root of the each element 
 [[2. 4.]
 [6. 9.]]


In [43]:
x=np.array([[2,3,4],[6,1,2]])
y=np.array([[5,1,2],[4,2,3]])
print("maximum value by element wise: \n",np.maximum(x,y))

maximum value by element wise: 
 [[5 3 4]
 [6 2 3]]


In [3]:
arr1=np.random.randn(100)
arr1

array([-0.10142999,  1.76676833,  0.58767123,  0.93945103,  0.66588371,
       -0.04580209, -0.46645616,  0.99168093, -0.77754259,  1.03130882,
        1.86149562,  0.51378824, -0.20966563, -0.26366505,  0.6651435 ,
        0.27339907, -1.74479463, -0.02050544, -0.77328218,  0.20252866,
       -1.20014995,  1.28353621,  1.35002409,  0.02981644,  0.26710197,
        0.58497498, -1.80924204,  0.87735572,  0.01100254,  1.65124581,
        0.0770837 , -1.44067496,  0.04712552,  1.42739354, -0.99460728,
       -0.33472413, -0.71650906,  0.05095632, -0.3605545 ,  0.90393912,
       -0.69777274,  0.27244605,  1.32279358,  0.56460617, -0.14365682,
       -0.10089833, -1.54083873,  0.31536236,  0.91537696,  0.36204909,
        0.80808889, -0.89373631,  0.58142691, -0.19695086,  0.48410622,
        0.70108851, -1.25825166,  0.90835767, -0.54835291, -0.33242749,
        0.20220455, -0.5723223 ,  2.63174634,  0.47500857, -0.32012601,
        0.16371821, -0.26776892, -1.25808544, -0.38412753,  1.05

In [5]:
arr1[arr1>0].sum()

43.620575579462965

In [13]:
#sort from traditional python
arr1=np.array([[13,4,5,11,3],[9,45,1,3,5]])
arr1.sort(axis=1)

In [14]:
arr1

array([[ 3,  4,  5, 11, 13],
       [ 1,  3,  5,  9, 45]])

In [18]:
# using numpy
arr1=np.array([[13,4,5,11,3],[9,45,1,3,5]])
sorted_arr1=np.sort(arr1)
print(sorted_arr1)

[[ 3  4  5 11 13]
 [ 1  3  5  9 45]]


In [20]:
#unique values
arr2=np.array(["nidhi","nidhi","pokemon","pokemon","nidhi","niks"])
np.unique(arr2)

array(['nidhi', 'niks', 'pokemon'], dtype='<U7')

In [31]:
arr1=np.arange(36)
print(arr1)
arr1.reshape((4,-1))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [35]:
#reval() and flatten()
arr1=np.random.randint(2,10,(4,4))
#ravel()
arr1.ravel()

array([2, 8, 6, 4, 2, 3, 4, 7, 5, 4, 8, 8, 5, 4, 7, 4])

In [36]:
arr1

array([[2, 8, 6, 4],
       [2, 3, 4, 7],
       [5, 4, 8, 8],
       [5, 4, 7, 4]])

In [37]:
arr1.flatten()

array([2, 8, 6, 4, 2, 3, 4, 7, 5, 4, 8, 8, 5, 4, 7, 4])

In [38]:
arr1

array([[2, 8, 6, 4],
       [2, 3, 4, 7],
       [5, 4, 8, 8],
       [5, 4, 7, 4]])

In [45]:
# concatenate of array
a1=np.array([[1,2,3,4],[2,3,1,3]])
a2=np.array([[4,3,1,2],[5,6,7,6]])
a3=np.concatenate((a1,a2),axis=1)
print(a3)

[[1 2 3 4 4 3 1 2]
 [2 3 1 3 5 6 7 6]]


In [49]:
# hstack and vstack
a1=np.array([[1,2,3,4],[2,3,1,3]])
a2=np.array([[4,3,1,2],[5,6,7,6]])
print("hstack: \n",np.hstack((a1,a2)))
print("vertical stack \n",np.vstack((a1,a2)))

hstack: 
 [[1 2 3 4 4 3 1 2]
 [2 3 1 3 5 6 7 6]]
vertical stack 
 [[1 2 3 4]
 [2 3 1 3]
 [4 3 1 2]
 [5 6 7 6]]
