In [2]:
import numpy as np

Create an array A with shape (3,3,3) and array B with shape (1,3,3) and perform the 
following:
1. Check the attributes of the array A.
2. Create a subarray by accessing sheet 0 (zero), all rows, flip order of all columns.
3. Reshape the array A into 2-Dimension array.
4. Addition and Multiplication with broadcasting.
5. Sum of all the elements, sum of each row and column of array A.

In [47]:
a=np.random.randint(2,20 ,size=(3,3,3))
b=np.random.randint(20,40,size=(1,3,3))
print(a)
print("\n")
print(b)

[[[ 6  6 16]
  [16  9  2]
  [17 15 16]]

 [[ 7 16  5]
  [17 15  6]
  [ 5 16 13]]

 [[ 3 11  5]
  [ 9 10  8]
  [18  6 14]]]


[[[20 35 21]
  [24 28 37]
  [34 31 24]]]


In [48]:
#attribute a
print("shape:",a.shape)
print("dimesion",a.ndim)
print("size",a.size)
print("types",a.dtype)

shape: (3, 3, 3)
dimesion 3
size 27
types int32


In [49]:
sub_a=a[0,:,::-1]
print(sub_a)

[[16  6  6]
 [ 2  9 16]
 [16 15 17]]


In [51]:
two_dim=a.reshape((9,3))
two_dim

array([[ 6,  6, 16],
       [16,  9,  2],
       [17, 15, 16],
       [ 7, 16,  5],
       [17, 15,  6],
       [ 5, 16, 13],
       [ 3, 11,  5],
       [ 9, 10,  8],
       [18,  6, 14]])

In [57]:
addition=a+b
print(addition)
print(addition.shape)

[[[26 41 37]
  [40 37 39]
  [51 46 40]]

 [[27 51 26]
  [41 43 43]
  [39 47 37]]

 [[23 46 26]
  [33 38 45]
  [52 37 38]]]
(3, 3, 3)


In [58]:
mul=a*b
print(mul)
print(mul.shape)

[[[120 210 336]
  [384 252  74]
  [578 465 384]]

 [[140 560 105]
  [408 420 222]
  [170 496 312]]

 [[ 60 385 105]
  [216 280 296]
  [612 186 336]]]
(3, 3, 3)


In [66]:
print("sum of all value in array a:\n",np.sum(a))
print("sum of the each row of array a:\n",np.sum(a,axis=1))
print("sum of the each column of array a:\n",np.sum(a,axis=2))

sum of all value in array a:
 287
sum of the each row of array a:
 [[39 30 34]
 [29 47 24]
 [30 27 27]]
sum of the each column of array a:
 [[28 27 48]
 [28 38 34]
 [19 27 38]]


In [71]:
#practice

In [77]:
a1=np.arange(2,42,2)
a2=a1.reshape(4,5)
a2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

In [79]:
np.random.rand(3,3)

array([[0.15355585, 0.16270479, 0.91028939],
       [0.34308936, 0.156922  , 0.2809797 ],
       [0.31499937, 0.85561794, 0.48076717]])

Create an array X using a routine of shape (4, 4) with values ranging from -10 to 10 and
compute the following:
1. Matrix rank of array
2. Determinant of an array and round the result for decimal place 1
3. Inverse of a matrix
4. Eigenvalues and right eigenvectors of a square array
5. Create subarrays of x into x1 (first 3 rows & 3 columns) and x2 (last 3 rows & last 3columns) and compute matrix product of two arrays (x1, x2)
6. Create subarrays of x into y1 (every other element of row & column) and y2 (everyother element from last row and last column) and compute dot and inner product of (y1, y2)
7. Raise a square matrix x1 to the power 3

In [82]:
x=np.random.randint(-10,10,(4,4))
print(x)

[[  2   7   8  -7]
 [ -1  -3   9  -2]
 [ -4  -8   6 -10]
 [ -4  -5  -7   5]]


In [87]:
print("rank of the matrix", np.linalg.matrix_rank(x))

rank of the matrix 4


In [91]:
print("determinent:",round(np.linalg.det(x),1))

determinent: -2610.0


In [92]:
print("diagonal:",np.diagonal(x))

diagonal: [ 2 -3  6  5]


In [94]:
#sum of the diagonal
print(sum(np.diagonal(x)))

10


In [103]:
eig_value,eig_vector=np.linalg.eig(x)
print("eigen value \n",eig_value)
print("eigen vector \n",eig_vector)

eigen value 
 [-2.88809395+0.j         -0.4477232 +8.08480004j -0.4477232 -8.08480004j
 13.78354035+0.j        ]
eigen vector 
 [[-0.82041743+0.j          0.53095025+0.j          0.53095025-0.j
  -0.68573176+0.j        ]
 [ 0.51888661+0.j         -0.01107036+0.52248881j -0.01107036-0.52248881j
  -0.1873849 +0.j        ]
 [-0.12962976+0.j         -0.50226383+0.15825172j -0.50226383-0.15825172j
  -0.28250402+0.j        ]
 [-0.20215846+0.j         -0.39942627+0.09011555j -0.39942627-0.09011555j
   0.64408877+0.j        ]]


In [120]:
x1=x[:3,:3]
x2=x[1:,1:]
print("matrix multiplication:\n",np.dot(x1,x2))

matrix multiplication:
 [[-102    4  -34]
 [ -18  -90   77]
 [  46 -126  118]]


In [125]:
y1=x[::2,::2]
print(y1,"\n")
y2=x[::-2,::-2]
print(y2)
print("inner matrix:\n",np.inner(y1,y2))

[[ 2  8]
 [-4  6]] 

[[ 5 -5]
 [-2 -3]]
inner matrix:
 [[-30 -28]
 [-50 -10]]


In [126]:
print(np.power(x1,3))

[[   8  343  512]
 [  -1  -27  729]
 [ -64 -512  216]]


Create a structured array with the columns specified in the table below and perform the 
following:
1. Create a copy of the original array and perform the operations on it.
2. Sort the array by ‘Salary’ column in descending order.
3. Create an array by accessing ‘Age’ column and perform an indirect sort on it to return array of indices, using these indices construct a sorted array via fancy indexing.
4. Create a subset of array where ‘Experience’ is greater than 20 (use where() function).
5. Create an array ‘Incentive’ by adding 200 to the salary for those who are having work experience more than 20 years.
6. Access ‘Name’, ‘Gender’ and ‘Age’ columns at once using a list of field names.
7. Access last two names of the array ‘Name’.
8. Use shorter syntax method to display the minimum, average, maximum and standard deviation of the salary.
9. Are all of the employees male?
10. How many employees are there with working experience between 15.2 and 24.5?


In [188]:
dt=np.dtype([('Name','S20'),('Gender','S20'),('Age','i4'),('Experience','float64'),('Salary','i')])
p_table= np.array([('cathy','F',45,15.5,2711), 
 ('Xavier','M',78,9.2,3420), 
 ('Alexander','M',61,24.1,3275), 
 ('Andrew','M',44,15.6,5988), 
 ('isabelle','F',45,15.9,7444),
 ('Natasha','F',61,24.5,1646), 
 ('Henry','M',60,24.5,1646), 
 ('David','M',47,15.3,9120)], dtype=dt) 
print(p_table)

[(b'cathy', b'F', 45, 15.5, 2711) (b'Xavier', b'M', 78,  9.2, 3420)
 (b'Alexander', b'M', 61, 24.1, 3275) (b'Andrew', b'M', 44, 15.6, 5988)
 (b'isabelle', b'F', 45, 15.9, 7444) (b'Natasha', b'F', 61, 24.5, 1646)
 (b'Henry', b'M', 60, 24.5, 1646) (b'David', b'M', 47, 15.3, 9120)]


In [189]:
b=p_table.copy()

In [190]:
(b[np.argsort(b["Salary"])])[::-1]

array([(b'David', b'M', 47, 15.3, 9120),
       (b'isabelle', b'F', 45, 15.9, 7444),
       (b'Andrew', b'M', 44, 15.6, 5988),
       (b'Xavier', b'M', 78,  9.2, 3420),
       (b'Alexander', b'M', 61, 24.1, 3275),
       (b'cathy', b'F', 45, 15.5, 2711), (b'Henry', b'M', 60, 24.5, 1646),
       (b'Natasha', b'F', 61, 24.5, 1646)],
      dtype=[('Name', 'S20'), ('Gender', 'S20'), ('Age', '<i4'), ('Experience', '<f8'), ('Salary', '<i4')])

In [191]:
#fancy indexing
age_1=b["Age"]
ind=np.argsort(age_1)
b[ind]

array([(b'Andrew', b'M', 44, 15.6, 5988),
       (b'cathy', b'F', 45, 15.5, 2711),
       (b'isabelle', b'F', 45, 15.9, 7444),
       (b'David', b'M', 47, 15.3, 9120), (b'Henry', b'M', 60, 24.5, 1646),
       (b'Alexander', b'M', 61, 24.1, 3275),
       (b'Natasha', b'F', 61, 24.5, 1646),
       (b'Xavier', b'M', 78,  9.2, 3420)],
      dtype=[('Name', 'S20'), ('Gender', 'S20'), ('Age', '<i4'), ('Experience', '<f8'), ('Salary', '<i4')])

In [192]:
b[np.where(b["Experience"]>20)]

array([(b'Alexander', b'M', 61, 24.1, 3275),
       (b'Natasha', b'F', 61, 24.5, 1646),
       (b'Henry', b'M', 60, 24.5, 1646)],
      dtype=[('Name', 'S20'), ('Gender', 'S20'), ('Age', '<i4'), ('Experience', '<f8'), ('Salary', '<i4')])

In [193]:
b[np.where(b["Experience"]>20)]["Salary"]+200

array([3475, 1846, 1846], dtype=int32)

In [194]:
b[["Name","Gender","Age"]]

array([(b'cathy', b'F', 45), (b'Xavier', b'M', 78),
       (b'Alexander', b'M', 61), (b'Andrew', b'M', 44),
       (b'isabelle', b'F', 45), (b'Natasha', b'F', 61),
       (b'Henry', b'M', 60), (b'David', b'M', 47)],
      dtype={'names':['Name','Gender','Age'], 'formats':['S20','S20','<i4'], 'offsets':[0,20,40], 'itemsize':56})

In [195]:
b["Name"][-2:]

array([b'Henry', b'David'], dtype='|S20')

In [196]:
b[["Name","Gender","Age"]][:2]

array([(b'cathy', b'F', 45), (b'Xavier', b'M', 78)],
      dtype={'names':['Name','Gender','Age'], 'formats':['S20','S20','<i4'], 'offsets':[0,20,40], 'itemsize':56})

In [197]:
print("minimum of salary",np.min(b["Salary"]))
print("maximum of salary",np.max(b["Salary"]))
print("average of salary",np.average(b["Salary"]))
print("standard deviation of salary",round(np.std(b["Salary"]),4))

minimum of salary 1646
maximum of salary 9120
average of salary 4406.25
standard deviation of salary 2605.608


In [198]:
b[b["Gender"]=="M"]

array([], shape=(0, 8),
      dtype=[('Name', 'S20'), ('Gender', 'S20'), ('Age', '<i4'), ('Experience', '<f8'), ('Salary', '<i4')])

In [204]:
print("number of persons experience between 15.2 and 24.5 is :",np.count_nonzero(b[(b["Experience"]>15.2)&(b["Experience"]<24.5)]))

number of persons experience between 15.2 and 24.5 is : 5


In [206]:
b

array([(b'cathy', b'F', 45, 15.5, 2711),
       (b'Xavier', b'M', 78,  9.2, 3420),
       (b'Alexander', b'M', 61, 24.1, 3275),
       (b'Andrew', b'M', 44, 15.6, 5988),
       (b'isabelle', b'F', 45, 15.9, 7444),
       (b'Natasha', b'F', 61, 24.5, 1646),
       (b'Henry', b'M', 60, 24.5, 1646), (b'David', b'M', 47, 15.3, 9120)],
      dtype=[('Name', 'S20'), ('Gender', 'S20'), ('Age', '<i4'), ('Experience', '<f8'), ('Salary', '<i4')])

In [210]:
# name of peoples who age is greater than 50
b[b["Age"]>50]["Name"]

array([b'Xavier', b'Alexander', b'Natasha', b'Henry'], dtype='|S20')